### ISSUE TITLE
Add ACL with login screen

### ISSUE THREAD

**Issue by remie** [remie/YouTransfer#105]
This needs some thorough planning... adding ACL will require a login screen, some sort of password retrieval option, and user management options in the settings screen. 

Perhaps it would be more easy to implement it using one of the existing [Passport](https://github.com/jaredhanson/passport) authentication modules with a simply approve / revoke screen.

**Comment by dangamba** [comment]
+1

**Comment by tristan-k** [comment]
+1

**Comment by samuelvonstachelski** [comment]
:+1:

**Comment by chiarishow** [comment]
Great missing feature.

In my option in this ACL a great role can be the "uploader" , it means that only the "uploader" can upload something and everyone can download. Like many file sharing platform. 

Thank you.

**Comment by InfernoZeus** [comment]
FWIW, I chose this project explicitly because it didn't have any sort of ACL/user management. Could this feature perhaps be put behind an option flag?

**Comment by remie** [comment]
@InfernoZeus : it will definitely be configurable. By default, it will remain as is (without authentication) and the access restriction will have to be explicitly set. Once set, it will still be possible to control the permissions of anonymous users, allowing them to upload (but for instance restrict downloading the files) without having to log in.

**Comment by InfernoZeus** [comment]
@remie That sounds perfect!

**Comment by remie** [comment]
That was an unfortunate mistake... the cherry-pick of a fix should not have closed this issue.
