### ISSUE TITLE
Rewrite file upload to use streams to support files greater than 1GB (fix for "RangeError" because of node memory limitations)

### ISSUE THREAD

**Issue by ktruckenmiller** [remie/YouTransfer#136]
Any idea on how we can increase this?

**Comment by remie** [comment]
@ktruckenmiller : you can set the NodeJS memory allocation at the command-line. https://github.com/nodejs/node-v0.x-archive/wiki/FAQ#what-is-the-memory-limit-on-a-node-process

**Comment by ktruckenmiller** [comment]
I've had success in just doing a readable/writeable stream.  That way you don't have to worry about how large the file is. 

https://github.com/ktruckenmiller/YouTransfer/blob/master/lib/localstorage.js#L51

**Comment by remie** [comment]
Ok, fair enough, this can also be fixed properly :)
But shouldn't you be able to make this a lot simpler by just piping the read stream to the write stream?

**Comment by ktruckenmiller** [comment]
Yes that would be much better as well.

**Comment by remie** [comment]
@ktruckenmiller : tested it with a 10GB file and it works like a charm. BTW, I did notice that you've been making a lot of changes in your fork. You might have some issues updating to the latest upstream version...
