### ISSUE TITLE
Use full width for Upload when Download is disabled

### ISSUE THREAD

**Issue by InfernoZeus** [remie/YouTransfer#139]
If you disable the File Download feature, the Upload pane on the homepage is still restrained to the left half of the page. Could this perhaps expand to fill all of the available space?
![screenshot from 2015-10-13 17-29-22](https://cloud.githubusercontent.com/assets/283676/10459490/0026ef02-71d0-11e5-9ade-fb5f886f0752.png)

**Comment by remie** [comment]
Mmm... yeah... that doesn't look nice at all. It was a conscious decision to make it half-sized as it kind of looks better than having a lot of white space. But it does limit the amount of characters you can use for the (sub)title. This should definitely be fixed and the easiest way to do so is to indeed stretch the container. But if there's a better idea which is more aesthetic I'm open to suggestions!

**Comment by InfernoZeus** [comment]
Personally, I don't mind the extra white space from having it full width (although my laptop screen isn't that high res!)
![screenshot from 2015-10-14 10-26-50](https://cloud.githubusercontent.com/assets/283676/10478492/3e807712-725e-11e5-9354-46f033be1893.png)
Alternatively, you could just center the main pane?
![screenshot from 2015-10-14 10-27-12](https://cloud.githubusercontent.com/assets/283676/10478501/4bab7734-725e-11e5-9513-47806ac89ba3.png)

**Comment by remie** [comment]
@InfernoZeus :+1: I'll stretch the panel full width. It doesn't look that bad second time around.
